### ISSUE TITLE
Bugs and Features

### ISSUE THREAD

**Issue by Mikael-R** [MateusSoares895/socket.client#2]
### Features
1) Swap mouse icon when passed by a button
2) Add a keyboard shortcut to cancel the adicition a request (prefernce ESC)
3) Add icon

### Bugs
1) The request name is "overwrite" the pupup
2) Screen size dont have a limit
3) On close window the process continues running

**Comment by mateushnsoares** [comment]
I'm coding a commit before there I will develop these features and fix these bugs

**Comment by mateushnsoares** [comment]
I'm developing these features and bugs but not will add icon because I assume that is not really necessary in the development process I will add on the build.
And the popup not overwriting the request name ( It's possible I adjusted it without want ).
And the process continues running I think that is not possible close because when run I don't have control of the process
